# value statement start
upload-path: E:/trading-system/upload/
front-path: E:/trading-system/front/
ip-address: http://localhost:8080/
# upload-path: /usr/local/trading-system/upload/
# front-path: /usr/local/trading-system/front/
# value statement end

server:
  port: 8080
spring:
  application:
    name: trading-system
  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
  # database connection config start
  datasource:
    username: root
    password: mynameis123
    url: jdbc:mysql://localhost:3306/tradingsystem?useUnicode=true&serverTimeZone=UTC&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat, wall, slf4j
      filter:
        stat: # spy
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall: # firewall
          enabled: true
          config:
            drop-table-allow: false
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
  # database connection config end

  output:
    ansi:
      enabled: detect

  # thymeleaf config start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  # thymeleaf config end

  # road config start
  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public, file:${upload-path}, file:${front-path}
# road config end



# mybatis config start
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# mybatis config end


# log config start
logging:
  level:
    com.frye.trading.dao: debug
# log config end